version: 2

builds:
  - main: .
    binary: mage-os-install
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - binary

checksum:
  name_template: 'checksums.txt'
