version: 2

builds:
  - main: .
    binary: mage-os-install
    ldflags:
      - -s -w -X main.version={{ .Tag }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - binary
    name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'
